<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GET AN INSTANT REPLY_hs-button primary large</name>
   <tag></tag>
   <elementGuidId>2adf75db-5be3-4218-b4cb-513ad511a2ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.hs-button.primary.large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e89303f7-b5d0-4c06-9cf3-bccc2c7b851b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>32a4cdfc-7481-4dd2-b59c-6d98a5e87b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-button primary large</value>
      <webElementGuid>183708b9-cedb-4961-aa49-e32bb8190aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>6a4b6e5c-22f6-484f-b22a-578d31eabc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hsForm_2498076a-5d90-479f-b2e2-69f688bbdd66&quot;)/div[@class=&quot;hs_submit hs-submit&quot;]/div[@class=&quot;actions&quot;]/input[@class=&quot;hs-button primary large&quot;]</value>
      <webElementGuid>f4ec60b1-bf82-4c68-a4f0-11aefe4e417a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Submit']</value>
      <webElementGuid>6ae2f522-09d3-4ca1-8800-47bc5fcb5e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_2498076a-5d90-479f-b2e2-69f688bbdd66']/div/div[2]/input</value>
      <webElementGuid>8a4fb7a1-6db6-45f7-93e6-d2fb43dce085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9fc84e6f-f6dd-4f37-9725-828bc4086c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>18ae419c-d393-4bbe-aef5-90f4aba9537c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
